### ISSUE TITLE
Build version 0.3.1 mistakenly contains all leafy artifacts, also document the release process.

### ISSUE THREAD

**Issue by blaines** [lookout/leafy#44] opened 2015-04-20 21:21 UTC
1. The Leafy metrics gem archive contains everything, not just leafy. 

```
1.7.13@repo master ~/···/services/repo> gem which leafy-metrics
/Users/bschanfeldt/.rvm/gems/jruby-1.7.13@repo/gems/leafy-metrics-0.2.1/lib/leafy-metrics.rb

1.7.13@repo master ~/···/services/repo> ls -al /Users/bschanfeldt/.rvm/gems/jruby-1.7.13\@repo...
total 56
drwxr-xr-x   14 blaines  Users   476 Apr 20 14:14 .
drwxr-xr-x  138 blaines  Users  4692 Apr 20 14:14 ..
-rw-r--r--    1 blaines  Users   567 Apr 20 14:14 .gitignore
-rw-r--r--    1 blaines  Users   417 Apr 20 14:14 .travis.yml
-rw-r--r--    1 blaines  Users   266 Apr 20 14:14 CHANGELOG.md
-rw-r--r--    1 blaines  Users    85 Apr 20 14:14 Gemfile
-rw-r--r--    1 blaines  Users  1075 Apr 20 14:14 LICENSE
-rw-r--r--    1 blaines  Users   702 Apr 20 14:14 README.md
drwxr-xr-x    4 blaines  Users   136 Apr 20 14:14 examples
-rw-r--r--    1 blaines  Users   769 Apr 20 14:14 leafy-complete.gemspec
drwxr-xr-x   10 blaines  Users   340 Apr 20 14:14 leafy-health
drwxr-xr-x   10 blaines  Users   340 Apr 20 14:14 leafy-logger
drwxr-xr-x   10 blaines  Users   340 Apr 20 14:14 leafy-metrics
drwxr-xr-x   10 blaines  Users   340 Apr 20 14:14 leafy-rack
```

2. Also the release process needs to be documented.

**Comment by mkristian** [comment] 2015-04-21 17:44
can not reproduce or understand what you mean
```
$ tree -d /home/christian/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/leafy-metrics-0.2.1/
/home/christian/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/leafy-metrics-0.2.1/
├── lib
│   ├── io
│   │   └── dropwizard
│   │       └── metrics
│   │           ├── metrics-core
│   │           │   └── 3.1.0
│   │           └── metrics-graphite
│   │               └── 3.1.0
│   ├── leafy
│   │   └── metrics
│   │       └── graphite
│   └── org
│       └── slf4j
│           └── slf4j-api
│               └── 1.7.7
└── spec

16 directories
```

**Comment by rtyler** [comment] 2015-04-21 17:54
@mkristian the problem is with the 0.3.1 version of the gem specifically, which either I built improperly, or for some other reason is including the entirety of the source tree.

**Comment by mkristian** [comment] 2015-04-21 18:13
ok - I did look in 0.2.1 and 0.3.0 but not in 0.3.1 :(

added some comments on releasing the gems to the readme. closing

**Closed by mkristian** 2015-04-21 18:13 UTC
